#@TYPE: Machine
#@NAME: 正点原子 i.MX6ULL 阿尔法
#@SOC: i.MX6ULL
#@DESCRIPTION: 512MB DDR，LAN8720 双网口，TF 卡启动（USDHC1），eMMC 在设备树中启用

MACHINEOVERRIDES =. "mx6ull:"

include conf/machine/include/imx-base.inc
include conf/machine/include/arm/armv7a/tune-cortexa7.inc

KERNEL_DEVICETREE = "nxp/imx/imx6ull-alientek-alpha.dtb"

UBOOT_MAKE_TARGET = "u-boot.imx"
UBOOT_SUFFIX = "imx"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "mx6ull_alientek_alpha_config"

UBOOT_ENV = "boot"
UBOOT_ENV_SUFFIX = "scr"

SERIAL_CONSOLES = "115200;ttymxc0"

MACHINE_FEATURES = "usbgadget usbhost vfat ext2 alsa"

IMAGE_BOOT_FILES = " \
    zImage \
    imx6ull-alientek-alpha.dtb \
    boot.scr \
"

WKS_FILE = "imx-uboot-bootpart.wks.in"
