BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "alientek"
BBFILE_PATTERN_alientek = "^${LAYERDIR}/"
BBFILE_PRIORITY_alientek = "8"
LAYERDEPENDS_alientek = "core freescale-layer openembedded-layer swupdate"
LAYERSERIES_COMPAT_alientek = "scarthgap wrynose"
